### ISSUE TITLE
Doesnt shutdown 

### ISSUE THREAD

**Issue by oxicottin** [FaserF/ControlPCWithVoice#2]
Hello, I cant get this to shut PC down but it will create the IFTTT folder and file on dropbox. I am running Win 7 and tried running powershell as admin with the two lines.
1) Set-ExecutionPolicy Unrestricted﻿
2) set-executionpolicy -executionpolicy unrestricted

In the scheduler if I hit the "Run" the black box comes up and my PC will shut down, It wont do it by google voice command though. I Cant figure out why its not shutting down...

**Comment by FaserF** [comment]
Hi,
Sorry I forgot to add, that these commands only have to be used on Windows 10 as I got to know.

Could you test the following things:
- If you tell Google to shut down your PC, will it answer the sentence you have added in IFTTT (should be something like "Okay, I will shut it down")?
- If Google answers you, is a new file created in your Dropbox folder?

If the above things work, then your settings in IFTTT are correct. If not, start from the scratch and configure IFTTT again.
If they work it has something to do with the script.
If you hit run in the scheduler no black screen should pop up. Then there is some kind of mistake. For the issue that your PC will instantly shut down after run, could you check if the shutdown.txt exists in your Dropbox folder? If yes, delete it.

**Comment by oxicottin** [comment]
Ok, I told my PC to shut down and it gave the command I said to in IFTTT like "Shutting down HTPC now" so that was good. Next, a .txt file in dropbox/IFTTT/shutdown.txt  is created and nothing happens. Now if I open scheduler there is a message under last run result. 

The operation being requested was not performed because the user was not logged onto the network.  The specified service does not exist (0x800704DD)

Now, there is one thing I have different and its in the scheduler. This is my HTPC so I dont have a password on it so under General in the scheduler I ticked "Run only when user is logged on" because it wont allow me to tick "Run whether user is logged on or not" if I dont have a password to log in.

Could this be why I dont think so.... anyway I click "Run" and the black box comes up with nothing in it. If I close the box with the X nothing happens BUT if I click inside the box then my PC shuts down.

The black box title is "Administrator: taskeng.exe"

**UPDATE SOLVED:**

OK it was the "Run whether user is logged on or not" you have to have it ticked! so what I did was used this [Automatically Login To Windows, Without Typing Any Password](https://www.digitalcitizen.life/log-automatically-windows-7-without-typing-your-password) and bypassed it on bootup. Sorry for the confusion and thank you for the hard work and response!
