### ISSUE TITLE
Not really an issue, would like advice. 

### ISSUE THREAD

**Issue by LilPeen** [FaserF/ControlPCWithVoice#3]
I have modified your script quite a bit to remove what i wouldn't use and add in some features i would use.

some of these involve using "Displaylink.exe /external" etc. to switch between which monitors are on/off. 

The Script run right from the Directory or Powershell: Perfect.

Script Run from Task Scheduler, Full elevation, all steps taken from vids and other issues: All But Display Commands. 

#Declaring Variables
$ScriptDirectory = "C:\Scripts"
$SearchDirectory = "E:\Dropbox\IFTTT"
$Extd = 'displayswitch.exe /extend'
$Int = 'displayswitch.exe /internal'
$Ext = 'displayswitch.exe /external'

$SleepTime = 5

cd $ScriptDirectory

#Sleep for 30 Seconds before being active (to prevent boot loops if the file for some reason is not deleted)
Start-Sleep -Seconds 15

#Loop checking to see if the file has been created and once it has it continues on. Sleep in the look to prevent CPU pegging
Do {
Start-Sleep -Seconds $SleepTime
$shutdown = Test-Path -Path "$SearchDirectory\shutdown.txt"
$reboot = Test-Path -Path "$SearchDirectory\reboot.txt"
$louder = Test-Path -Path "$SearchDirectory\louder.txt"
$quieter = Test-Path -Path "$SearchDirectory\quieter.txt"
$50percent = Test-Path -Path "$SearchDirectory\50percent.txt"
$25percent = Test-Path -Path "$SearchDirectory\25percent.txt"
$75percent = Test-Path -Path "$SearchDirectory\75percent.txt"
$mute = Test-Path -Path "$SearchDirectory\mute.txt"
$external = Test-Path -Path "$SearchDirectory\external.txt"
$internal = Test-Path -Path "$SearchDirectory\internal.txt"
$extend = Test-Path -Path "$SearchDirectory\extend.txt"
$headphones = Test-Path -Path "$SearchDirectory\headphones.txt"
}

Until ($shutdown -eq $True -or $reboot -eq $True -or $hibernate -eq $True -or $louder -eq $True -or $quieter -eq $True -or $50percent -eq $True -or $25percent -eq $True -or $75percent -eq $True -or $mute -eq $True -or $external -eq $True -or $internal -eq $True -or $extend -eq $True -or $headphones -eq $True)
#-or $soundcloud-next -eq $True)

#Shutdown
if ($shutdown -eq $True) {
#Removes the shutdown file to prevent an imediate shutdown when the computer starts back up
Remove-Item -Path "$SearchDirectory\shutdown.txt"
#Shuts the computer down forcefully but gracefully
Stop-Computer -Force
}

#Reboot
if ($reboot -eq $True) {
#Removes the reboot file to prevent an imediate reboot when the computer starts back up
Remove-Item -Path "$SearchDirectory\reboot.txt"
#Reboots the computer forcefully but gracefully
Restart-Computer -Force
}

#Volume Up
if ($louder -eq $True) {
#Removes the Volume file to prevent changing volume on startup
Remove-Item -Path "$SearchDirectory\louder.txt"
#Starting volume up
nircmd.exe setdefaultsounddevice "Monitor2" 1
nircmd.exe changesysvolume 9750
.\VC.ps1
}

#Volume Down
if ($quieter -eq $True) {
#Removes the Volume file to prevent changing volume on startup
Remove-Item -Path "$SearchDirectory\quieter.txt"
#Starting volume down
nircmd.exe setdefaultsounddevice "Monitor2" 1
nircmd.exe changesysvolume -9750
.\VC.ps1
}

#Volume 50%
if ($50percent -eq $True) {
#Removes the Volume file to prevent changing volume on startup
Remove-Item -Path "$SearchDirectory\50percent.txt"
#Starting volume 50%
nircmd.exe setdefaultsounddevice "Monitor2" 1
nircmd.exe setsysvolume 32767.5
.\VC.ps1
}

#Volume 25%
if ($25percent -eq $True) {
#Removes the Volume file to prevent changing volume on startup
Remove-Item -Path "$SearchDirectory\25percent.txt"
#Starting volume 25%
nircmd.exe setdefaultsounddevice "Monitor2" 1
nircmd.exe setsysvolume 16383.75
.\VC.ps1
}

#Volume 75%
if ($75percent -eq $True) {
#Removes the Volume file to prevent changing volume on startup
Remove-Item -Path "$SearchDirectory\75percent.txt"
#Starting volume 75%
nircmd.exe setdefaultsounddevice "Monitor2" 1
nircmd.exe setsysvolume 49151.25
.\VC.ps1
}

#Mute%
if ($mute -eq $True) {
#Removes the Volume file to prevent changing volume on startup
Remove-Item -Path "$SearchDirectory\mute.txt"
#Starting mute%
nircmd.exe setdefaultsounddevice "Monitor2" 1
nircmd.exe mutesysvolume 2
.\VC.ps1
}

#external Display%
if ($external -eq $True) {
#externalDisplay Only
Remove-Item -Path "$SearchDirectory\external.txt"
#Starting external%
Invoke-Expression $Ext
.\VC.ps1
}

#internal Display%
if ($internal -eq $True) {
#externalDisplay Only
Remove-Item -Path "$SearchDirectory\internal.txt"
#Starting internal%
Invoke-Expression $Int
.\VC.ps1
}

#extend Display%
if ($extend -eq $True) {
#Both Displays
Remove-Item -Path "$SearchDirectory\extend.txt"
#Starting extend%
Invoke-Expression $Extd 
.\VC.ps1
}

#Switch To Headphones%
if ($headphones -eq $True) {
#Route Audio to headphones
Remove-Item -Path "$SearchDirectory\headphones.txt"
#Starting extend%
nircmd.exe setdefaultsounddevice "Headphones" 1
.\VC.ps1
}

Any help would be greatly appreciated.

**Comment by LilPeen** [comment]
For some reason, just switching it to run as "Users" with a -windowstyle Hidden did the trick. 

My apologies for the wasted Post!

**Comment by FaserF** [comment]
Hi LilPeen,
Your post was definitely not wasted.
The idea with Displaylink.exe /external is awesome and especially for Netflix and co great. I am a user with 3 screens and I will definitely implement your idea.

**Comment by LilPeen** [comment]
Appreciate it, now idk much powershell most of this was a crash course of about two days.. but i am revisiting your netflix option but i set it to first switch to the second monitor (its my video screen) before triggering, i look forward to your updates, and ill add anything ive done to this thread if you're interested (not sure there is a better place, literally made a github account for this)
